#!/usr/bin/env bash

LOCAL_DIR="$HOME/.local"

[ "$(uname)" = "Linux" ] && sudo apt update

install() {
  COMMAND=$1
  PACKAGE=$COMMAND
  [ "$COMMAND" = "trash" ] && PACKAGE="trash-cli"
  [ "$COMMAND" = "nvim" ] && PACKAGE="neovim"
  [ "$COMMAND" = "ag" ] && PACKAGE="silversearcher-ag"
  [ "$COMMAND" = 'fzf' ] && install_fzf, return

  echo ">>> Installing $PACKAGE..."

  if ! command -v "$COMMAND" >/dev/null 2>&2; then
    [ "$(uname)" = "Darwin" ] && brew install "$PACKAGE"
    [ "$(uname)" = "Linux" ] && sudo apt install -y "$PACKAGE"
  else
    echo "$PACKAGE has already installed on your system"
  fi
  echo ""
}

install_fzf() {
  if [ -d ~/.local/fzf ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.local/fzf
    # shellcheck disable=SC1090
    . ~/.local/fzf/install
  fi
}
