#!/usr/bin/env bash

[ "$(uname)" = "Linux" ] && sudo apt update

install_package() {
  COMMAND=$1
  PACKAGE=$2
  if ! command -v "$COMMAND" >/dev/null 2>&2; then
    [ "$(uname)" = "Darwin" ] && brew install "$PACKAGE"
    [ "$(uname)" = "Linux" ] && sudo apt install -y "$PACKAGE"
  else
    echo "$PACKAGE has already installed on your system"
  fi
}

install_fzf() {
  if [ -d ~/.local/fzf ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.local/fzf
    # shellcheck disable=SC1090
    . ~/.local/fzf/install
  fi
}

install() {
  echo ">>> Installing $1..."
  declare -A CMD_PKG
  COMMAND=$1
  CMD_PKG=(["trash"]="trash-cli" ["nvim"]="neovim" ["ag"]="silversearcher-ag")

  if [ "$COMMAND" = 'fzf' ]; then
    install_fzf
  else
    PACKAGE=$COMMAND
    [[ -z ${CMD_PKG["$COMMAND"]} ]] && PACKAGE=${CMD_PKG["$COMMAND"]}
    install_package "$COMMAND" "$PACKAGE"
  fi

  echo ""
}
