# All SpaceVim option below [option] section
[options]
  colorscheme = "SpaceVim"
  colorscheme_bg = "dark"
  enable_guicolors = true
  statusline_separator = "nil"
  statusline_iseparator = "bar"
  buffer_index_type = 4
  enable_tabline_filetype_icon = false
  enable_statusline_mode = true
  autoindent = true

  relativenumber = true
  guifont = "Jetbrains Mono:h12"

  enable_vimfiler_welcome = true
  bootstrap_after = 'myspacevim#after'

[[layers]]
  name = "default"

[[layers]]
  name = "fzf"

[[layers]]
  name = 'autocomplete'
  auto_completion_tab_key_behavior = "smart"
  enable = false

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 25

[[layers]]
  name = "sudo"

[[layers]]
  name = "telescope"

[[layers]]
  name = 'lang#markdown'
  enable = false

[[layers]]
  name = 'git'

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "tmux"

[[layers]]
  name = "tools"

[[layers]]
  name = 'lang#dockerfile'

[[layers]]
  name = 'lang#python'
  python_interpreter='python3'
  python_file_head = ['']
  enable_typeinfo=true
  format_on_save=true

[[layers]]
  name = 'lsp'
  enabled_clients=['pyright']

