# All SpaceVim option below [option] section
[options]
  colorscheme = "SpaceVim"
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  statusline_separator = "nil"
  statusline_iseparator = "bar"
  buffer_index_type = 4
  enable_tabline_filetype_icon = false
  enable_statusline_mode = true

  relativenumber = true
  guifont = "Jetbrains Mono:h14"

  enable_vimfiler_welcome = false
  bootstrap_after = 'myspacevim#after'

[[layers]]
  name = "default"

[[layers]]
  name = 'autocomplete'
#auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 25

[[layers]]
  name = "sudo"

[[layers]]
  name = "telescope"

[[layers]]
  name = 'lang#markdown'
  enable = true

[[layers]]
  name = 'git'
  enable = true

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "tmux"
  enable = true

[[layers]]
  name = "tools"

[[layers]]
  name = 'lang#dockerfile'

[[layers]]
  name = 'lang#python'
  python_interpreter='python3'
  python_file_head = ['']
  enable_typeinfo=true
  format_on_save=true
  enabled_linters=['python3', 'pylint']

[[layers]]
  name = "lsp"
  enabled_clients = ['pyright']
